### ISSUE TITLE
MDN official style guide and examples have semicolons

### ISSUE THREAD

**Issue by noRubidium** [DarkPurple141/js-primer#11]
Style guide:
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style
(https://developer.mozilla.org/en-US/docs/User:GavinSharp_JS_Style_Guidelines)

Example:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

So does google style guide
https://google.github.io/styleguide/jsguide.html

**Comment by DarkPurple141** [comment]
Meh maybe we can change over. I've never had a no semicolon issue since I stopped using them,
but in the interests of defensive best practices we can use them.

**Comment by DarkPurple141** [comment]
Counterpoint:

* No semicolons in Vue.js src.
* No semicolons in bootstrap src.
* Brendan Eich doesn't use them.
* Tim Berners-Lee doesn't use them.

**Comment by noRubidium** [comment]
Most of the online style guides are using them and there are far more issues than just semicolons. I have fixed most of them up.

**Comment by DarkPurple141** [comment]
kk. I guess we'll use semi-colons then :(. OS feels all over again.

**Comment by noRubidium** [comment]
The other thing is semicolon makes a clear distinguish between statement, function declaration and control-structures. I would highly recommend using them since it makes your code much more clear.

Other than that if we just keep listing project that use/not-use semicolon I would say it's a very pointless discussion because there are millions of project out there than adopt different ideology.

In the end, there's no point trying to be different from C. Not that C-like is a bad thing. And semicolon is just a very small aspect I can't just say that if I don't use semicolon then it's a python-like language. The link you have shared said nothing about  whether having no semicolons  is good or not.

**Comment by noRubidium** [comment]
Sorry bad internet just saw it lol.

**Comment by DarkPurple141** [comment]
I agree that there be no divergence from C-like for no reason but I don't necessarily agree on the value of ending statements with ; being somehow more readable. Most statements are one line by definition. You can distinguish just as easily with proper whitespace use. But I also concede that the majority of style is pro-semi-colons.
